# Generated by Django 5.2.7 on 2025-12-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField()),
                ('city_name', models.CharField()),
                ('roll_number', models.IntegerField(default=101)),
                ('school_name', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('addmission_in_school', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
