# Generated by Django 5.2.7 on 2025-12-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
