# Generated by Django 5.2.7 on 2025-12-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teacher_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='aadhar_number',
            new_name='adhar_number',
        ),
    ]
