# Generated by Django 5.2.7 on 2025-12-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentinfo_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='year_in_school',
            field=models.CharField(blank=True, null=True),
        ),
    ]
