# Generated by Django 5.2.7 on 2025-12-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
    ]
